
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 혹은 update
    show-sql: true # 콘솔에서 날아가는 SQL 쿼리문을 보여줌
    properties:
      hibernate:
        format_sql: true # SQL을 보기좋게 정렬해서 보여줌
        dialect: org.hibernate.dialect.MySQL8Dialect
  #    defer-datasource-initialization: true # Hibernate 초기화 후 data.sql 실행

  sql:
    init:
      mode: never # 이 설정을 always로 해두면 data.sql이 항상 꽂힌다.

  security:
    oauth2:
      client:
        registration:
          google:
            # 💡 구글 클라우드 콘솔에서 발급받은 정보를 여기 넣어야 해!
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: debug              # 실제 실행되는 SQL 확인
    org.hibernate.type.descriptor.sql: trace # SQL에 들어가는 파라미터 값 확인
    org.springframework.orm.jpa: debug
    org.springframework.security: debug