-- 구약 성경 (Old Testament)
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (1, '창세기', 'Genesis', 50, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (2, '출애굽기', 'Exodus', 40, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (3, '레위기', 'Leviticus', 27, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (4, '민수기', 'Numbers', 36, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (5, '신명기', 'Deuteronomy', 34, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (6, '여호수아', 'Joshua', 24, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (7, '사사기', 'Judges', 21, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (8, '룻기', 'Ruth', 4, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (9, '사무엘상', '1 Samuel', 31, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (10, '사무엘하', '2 Samuel', 24, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (11, '열왕기상', '1 Kings', 22, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (12, '열왕기하', '2 Kings', 25, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (13, '역대상', '1 Chronicles', 29, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (14, '역대하', '2 Chronicles', 36, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (15, '에스라', 'Ezra', 10, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (16, '느헤미야', 'Nehemiah', 13, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (17, '에스더', 'Esther', 10, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (18, '욥기', 'Job', 42, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (19, '시편', 'Psalms', 150, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (20, '잠언', 'Proverbs', 31, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (21, '전도서', 'Ecclesiastes', 12, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (22, '아가', 'Song of Songs', 8, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (23, '이사야', 'Isaiah', 66, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (24, '예레미야', 'Jeremiah', 52, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (25, '예레미야 애가', 'Lamentations', 5, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (26, '에스겔', 'Ezekiel', 48, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (27, '다니엘', 'Daniel', 12, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (28, '호세아', 'Hosea', 14, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (29, '요엘', 'Joel', 3, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (30, '아모스', 'Amos', 9, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (31, '오바댜', 'Obadiah', 1, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (32, '요나', 'Jonah', 4, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (33, '미가', 'Micah', 7, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (34, '나훔', 'Nahum', 3, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (35, '하박국', 'Habakkuk', 3, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (36, '스바냐', 'Zephaniah', 3, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (37, '학개', 'Haggai', 2, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (38, '스가랴', 'Zechariah', 14, 'OLD');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (39, '말라기', 'Malachi', 4, 'OLD');

-- 신약 성경 (New Testament)
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (40, '마태복음', 'Matthew', 28, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (41, '마가복음', 'Mark', 16, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (42, '누가복음', 'Luke', 24, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (43, '요한복음', 'John', 21, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (44, '사도행전', 'Acts', 28, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (45, '로마서', 'Romans', 16, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (46, '고린도전서', '1 Corinthians', 16, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (47, '고린도후서', '2 Corinthians', 13, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (48, '갈라디아서', 'Galatians', 6, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (49, '에베소서', 'Ephesians', 6, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (50, '빌립보서', 'Philippians', 4, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (51, '골로새서', 'Colossians', 4, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (52, '데살로니가전서', '1 Thessalonians', 5, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (53, '데살로니가후서', '2 Thessalonians', 3, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (54, '디모데전서', '1 Timothy', 6, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (55, '디모데후서', '2 Timothy', 4, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (56, '디도서', 'Titus', 3, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (57, '빌레몬서', 'Philemon', 1, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (58, '히브리서', 'Hebrews', 13, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (59, '야고보서', 'James', 5, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (60, '베드로전서', '1 Peter', 5, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (61, '베드로후서', '2 Peter', 3, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (62, '요한일서', '1 John', 5, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (63, '요한이서', '2 John', 1, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (64, '요한삼서', '3 John', 1, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (65, '유다서', 'Jude', 1, 'NEW');
INSERT INTO bibles (id, kor_name, eng_name, total_chapter, testament) VALUES (66, '요한계시록', 'Revelation', 22, 'NEW');